---
abstract: 'a command-line RDAP client.'
author:
  - 'Gavin Brown <gavin.brown@uk.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.64, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: rdapper
no_index:
  directory:
    - t
    - inc
requires:
  Getopt::Long: 0
  HTTP::Request::Common: 0
  IO::Socket::SSL: 0
  JSON: 0
  JSON::Path: 0
  LWP: 6
  MIME::Base64: 0
  MIME::Type: 0
  Mozilla::CA: 0
  POSIX: 0
  Pod::Usage: 0
  URI: 0
version: 0.08
